name: Build and Upload to NPM Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun & Build Project
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build

    - name: Publish to NPM Packages
      run: bun publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
